# =============================================================================
# Dataset Information Module Configuration Template
# =============================================================================

# Analysis Parameters
analysis:
  detailed_chr_stats: true       # Generate per-chromosome statistics
  phenotype_analysis: true       # Analyze phenotype distributions
  population_structure: false    # Basic population structure analysis (PCA preview)
  
# Plotting Options
plots:
  histogram_bins: 50             # Number of bins for histograms
  figure_width: 10               # Plot width in inches
  figure_height: 8               # Plot height in inches
  dpi: 300                       # Plot resolution
  
# Output Options
output:
  generate_html_report: true     # Create comprehensive HTML report
  save_intermediate_files: true  # Keep intermediate PLINK output files
  compress_plots: false          # Compress plot files (PNG vs PDF)

# Software Modules (for HPC environments)
modules:
  load_modules: true                    # Enable module loading
  module_commands:
    - "module load plink2/1.90b3w"          # PLINK for genetic data analysis
    - "module load R"            # R for statistical analysis and plotting
    - "module load bcftools"      # BCFtools for VCF file handling
    - "module load vcftools"    # VCFtools for VCF manipulation
    - "module load htslib"        # HTSlib for genomic file formats
    - "module load samtools"      # SAMtools for sequence alignment files


# Resource Settings (for SLURM)
resources:
  cpus: 4
  memory_gb: 8
  time_hours: 2
  email: "alsammana@omrf.org"
